### ISSUE TITLE
Version number 

### ISSUE THREAD

**Issue by stvjfp1** [nickn17/evDash#16]
Just installed Evdash, but the version number says 1.8.3b? Should it not be 2.2.0?

**Comment by nickn17** [comment]
I tried now release branch / binary files via flashing tool for m5 stack . And there is in the menu v2.2.0.

**Comment by stvjfp1** [comment]
Strange, I have downloaded and binary files via flashing tool for m5 stack several times.  Same result, version 1.83b. Have not got my BLE4 unit yet, could it in a demo mode, until you connect the unit?

**Comment by nickn17** [comment]
If you hold left button during boot, evDash skip connecting to BLE & load
test data (static).

Ľ.



pi 1. 1. 2021 o 12:04 stvjfp1 <notifications@github.com> napísal(a):

**Comment by stvjfp1** [comment]
Can you see anything wrong in the log?

[evdash.txt](https://github.com/nickn17/evDash/files/5759084/evdash.txt)

**Comment by nickn17** [comment]
Btw did you recheck checkboxes? All fields have to be green, otherwise flasher dont write that files.

![image](https://user-images.githubusercontent.com/8830860/103441397-ed28d100-4c4d-11eb-9a1a-a3fe032a4114.png)

**Comment by stvjfp1** [comment]
Yes, I did, very strange.
![evdashpng](https://user-images.githubusercontent.com/52125379/103442402-1a797d00-4c56-11eb-8135-8127c52ed1ce.gif)

**Comment by stvjfp1** [comment]
Never tried the Erase button, perhaps erasing it would help?
But the strange thing is been on this version since, it first downloaded it 3 days ago.

**Comment by nickn17** [comment]
Please download it again. It seems that you downloaded old version. 

![image](https://user-images.githubusercontent.com/8830860/103453690-b4840880-4cdc-11eb-8bbb-b2d191a42016.png)

**Comment by stvjfp1** [comment]
Deleted and downloaded, even deleted and downloaded again the Flash Download Tool...
![20210102_123535](https://user-images.githubusercontent.com/52125379/103456575-b27b7300-4cf7-11eb-93b7-ab1f18ae4f41.jpg)
![20210102_123524](https://user-images.githubusercontent.com/52125379/103456576-b4453680-4cf7-11eb-9ab7-3eb569ebcc15.jpg)

**Comment by nickn17** [comment]
@stvjfp1 Could I check/flash it via Teamviewer? If yes, write me to nick.n17@gmail.com or via telegram https://t.me/lubos_petrovic

**Comment by stvjfp1** [comment]
Solved. Thank you.

**Comment by nickn17** [comment]
I just removed old enirodashboard.ino.bin files from release branch. Current version is named evDash.ino.bin
