### ISSUE TITLE
Hyundai Kona no speed kmh

### ISSUE THREAD

**Issue by stvjfp1** [nickn17/evDash#22]
Hyundai Kona 2019 64 kWh
evDash ver 2.2.0

No speed kmh.
![20210108_185828](https://user-images.githubusercontent.com/52125379/104052948-c25cf080-51ea-11eb-9efc-6bff16a35b75.jpg)

**Comment by nickn17** [comment]
Fixed in master branch.

**Comment by nickn17** [comment]
Pls, could you try it from master? Here is it .. 
https://github.com/nickn17/evDash/tree/master/dist/m5stack_core1
File: evDash.ino.bin

**Comment by stvjfp1** [comment]
That fixed it.
