### ISSUE TITLE
Celsius degrees

### ISSUE THREAD

**Issue by spairo1741** [nickn17/evDash#24]
hi, 
pls add celsius degrees like char(127).

![screenshot_2021_1_22_18_57_42](https://user-images.githubusercontent.com/29607074/105528341-2a303280-5ce5-11eb-9f50-3cfccb3d265d.png)
![screenshot_2021_1_22_18_57_31](https://user-images.githubusercontent.com/29607074/105528378-37e5b800-5ce5-11eb-8e5b-baf5f7b3da6e.png)

**Comment by nickn17** [comment]
char(127) added
