### ISSUE TITLE
Door open detection is inverted for right-hand drive cars

### ISSUE THREAD

**Issue by ebannon** [nickn17/evDash#25]
Minor issue. 2020 e-Niro
So open driver door (on the right) and the yellow indicator appears on the left of the device.
Not sure if this RHD/LHD info is even available from the car. If not, maybe a flag/preference under Settings could work

**Comment by nickn17** [comment]
Done for Niro/Kona and Ioniq. RHD option in the menu. Source code only, binary will be later.
https://github.com/nickn17/evDash/commit/305e68f6b46b9e9b797d4c3fe53233967cacd413
