### ISSUE TITLE
Bad value Consumption and Recuperation 

### ISSUE THREAD

**Issue by Josefino** [nickn17/evDash#26]
When the car is switching off, meaningless numbers are displayed in the values Consumption and Recuperation.
![evDash](https://user-images.githubusercontent.com/4889764/106378821-084f4380-63a8-11eb-9ac2-7b7356f3fefb.jpg)

**Comment by nickn17** [comment]
Could you test last release ? 
https://github.com/nickn17/evDash/tree/master/dist
