### ISSUE TITLE
No tire pressure & temperature show on display 

### ISSUE THREAD

**Issue by PeterAsztalos** [nickn17/evDash#29]
![IMG_0962](https://user-images.githubusercontent.com/79195411/108185457-9b101200-710c-11eb-8179-7abbcdbf4835.jpg)
Nezobrazuje sa mi aktualny tlak a teplota v pneumatikach. Mam poslednu verziu z decembra v2.2.0 2020-12-12, ostatne funkciu idu OK.
BLuet. mam tebou odporucany, Auto je to iste co mas ty :-)

Dakujem Lubos za tvoju reakciu.

Este jeden navrh na vylepsenie mam, doplnit k grafom o nabyjani informaciu od ktorej teploty plati ktory graf.
Prikladam moj navrh umiestnenia informacie.(teploty som si presne nepamatal su iba orientacne)
![IMG_1274 (1)](https://user-images.githubusercontent.com/79195411/108193517-d105c400-7115-11eb-8109-a6c067185fe1.jpg)

**Comment by nickn17** [comment]
Ahoj Peter. Prepáč za oneskorenú odpoveď. Vieš, pls skúsiť posledný master https://github.com/nickn17/evDash/tree/master/dist
Či tam ide ten tlak? Ak by nešiel budem potrebovať odchytiť výstup cez terminál. Pár sekúnd výstupu, keď sa zobrazujú údaje.

Ten návrh na vylepšie grafu super. Len ešte som nenašiel tak malý font.
