### ISSUE TITLE
When activate sdcard, cannot connect to BLE

### ISSUE THREAD

**Issue by dperez-sct** [nickn17/evDash#32]
My M5Stack with v2.2.0 2020-12-12 works without problem with BLE, until I activate sdcard. When I activate sdcard, the BLE keeps connecting and no connect.

Video with the problem -> https://www.youtube.com/watch?v=bywRsBJp_Xc

**Comment by nickn17** [comment]
SD card is working only with core2.
Core1 hasn't psram and there is a problem with memory.
