### ISSUE TITLE
MEB cars have constant meter flaw, instrumentation shows +3km/h in comparison to GPS.

### ISSUE THREAD

**Issue by MattiJarvinen** [nickn17/evDash#39]
MEB cars have constant meter flaw, instrumentation shows +3km/h in comparison to GPS with all speeds.

Do we want to collect the number shown in the instruments or the real value?

https://github.com/nickn17/evDash/blob/5f851ea6ebb8dde8f165d54382df89c911b993fe/src/CarVWID3.cpp#L327

**Comment by nickn17** [comment]
As you wish. I am displaying real kmh (gps) on Niro. Kona/Niro has bigger difference (+5-7kmh).

**Comment by MattiJarvinen** [comment]
Maybe just add that as a comment/note somewhere. I'm not really sure if this will change in the future OTA updates or is this related to tyre sizes. 🤔

Also is this really a bug worthy thing after all.

**Comment by ilachEU** [comment]
I don't have a GPS module and the control unit obviously knows the actual speed, and what it shows the driver is just a visual.  Because EVDash shows me a speed of just -3km / h compared to showing the car.  (Enyaq)

**Comment by nickn17** [comment]
> Also is this really a bug worthy thing after all.

Or add option to the settings ? Speed correction  -5 ... to +5 kmh ?

**Comment by nickn17** [comment]
Done.. Please could you check latest  master?
https://github.com/nickn17/evDash

There is an option in Others menu -> Speed correction
