### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by nickn17** [nickn17/evDash#6]
- [x]  Classes for boards and cars
- [ ]  Rewrite command queue
- [x]  Draw screne under board320_240
....

**Comment by ebannon** [comment]
Great project (and YouTube videos) 👍 

I realise you are refactoring the code at the moment. I think local file _struct.h_ has been removed but it's still referenced in some code - so cannot compile the project locally at this time. I'm trying to compile locally as flashing the most recent bin files is not working for me on two different TTGO devices which were working ok in the past.

**Comment by nickn17** [comment]
> Great project (and YouTube videos) 👍
> 
> I realise you are refactoring the code at the moment. I think local file _struct.h_ has been removed but it's still referenced in some code - so cannot compile the project locally at this time. I'm trying to compile locally as flashing the most recent bin files is not working for me on two different TTGO devices which were working ok in the past.

Did you update latest master branch? I compile it without success (updated before half hour). Or can you post me screenshot from your arduino error console to nick.n17@gmail.com. Several people compile this version without problems.

Btw you have to uncomment BOARD_TTGO_T4, and comment BOARD_M5STACK_CORE in evDash.ino
//#define BOARD_TTGO_T4
#define BOARD_M5STACK_CORE

**Comment by moravcik** [comment]
@ebannon try to checkout master Git branch, it is fixed there

**Comment by ebannon** [comment]
> @ebannon try to checkout master Git branch, it is fixed there

That's great. I got it working using the release branch in the end. 
Thank you both.
